#%RAML 0.8
title: 易邦生物
baseUri: http://server/api/
version: v0.1
mediaType: application/json

schemas:
  - respWithoutDataSchema: !include schema/resp-without-data.schema
  - respWithDataSchema: !include schema/resp-with-data.schema
  - respErrorSchema: !include schema/resp-error.schema
  - pagedSchema: !include schema/paged.schema

traits:
  # 接口响应中不包含data
  - respWithoutData:
      responses:
        200:
          body:
            application/json:
              schema: respWithoutDataSchema
              example: |
                {
                  "code": "0"
                }
  # 接口响应中包含data
  - respWithData:
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code": "0",
                  "data" : <<exampleData>>
                }
   # 接口响应错误
  - respError:
      responses:
        500:
          body:
            application/json:
              schema: respErrorSchema
              example: |
                {
                  "code": "9",
                  "msg" : <<msg>>
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>
  # 分页
  - paged:
      queryParameters:
          pageNumber:
            displayName: pageNumber
            description: 查询的页面编码，从1开始.如第六页=6
            type: integer
            minimum: 1
            required: false
            default: 1
            example: 6
          pageSize:
            displayName: pageSize
            description: 查询页面每页显示数据数量，如每页显示二十条数据=20
            type: integer
            maximum: 10 
            required: false
            default: 10
            example: 20
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code" : "0",
                  "data" : {
                    "pageNumber" : 1,
                    "pageSize" : 20,
                    "totalRow" : 362,
                    "list" : <<exampleList>>
                  }
                }
 

  # 查询用户权限
  - queryToken:
      queryParameters:
        username:
          displayName: username
          description: 用户唯一标志，使用32位UUID
          type: string
          required: true
          example: 72297c8842604c059b05d28bfb11d10b
        token:
          displayName: token
          description: 用户令牌
          type: string
          required: true
          example: 245accec3c124642967fe476cef558c4
  - bodyToken:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            username:
              displayName: username
              description: 用户唯一标志，使用32位UUID
              type: string
              required: true
              example: 72297c8842604c059b05d28bfb11d10b
            token:
              displayName: token
              description: 用户令牌
              type: string
              required: true
              example: 245accec3c124642967fe476cef558c4
              
#####################################################################
############################ 积分模块 ################################
#####################################################################
/api/{username}/{token}/jifen:
  displayName: 积分模块
  description: 积分模块
  uriParameters:
    username:
      displayName: username
      description: 用户唯一标志，使用32位UUID
      type: string
      required: true
      example: 72297c8842604c059b05d28bfb11d10b
    token:
      displayName: token
      description: 用户令牌
      type: string
      required: true
      example: 245accec3c124642967fe476cef558c4
      
  get:
    description: 查询当前积分
    is:
      - respWithData:
          exampleSchema: !include schema/biz/jifen.schema
          exampleData: | 
            {
              "point" : 58
            }
  /earn:
    displayName: 赚积分
    description: 赚积分，扫码赚积分、优惠券
    /scan/{id}:
      displayName: 扫码赚积分
      description: 扫码赚积分
      uriParameters:
        id:
          displayName: id
          description: 二维码唯一值
          type: string
          required: true
          example: 201602251234567890
      post:
        is:
          - respWithoutData:
          - respError:
              msg: "积分已领取，无法重复领取"
    /voucher/{id}:
      displayName: 商家优惠券
      description: 商家优惠券
      uriParameters:
        id:
          displayName: id
          description: 优惠券ID
          type: string
          required: true
          example: 1234567890
      post:
        is:
          - respWithoutData:
          - respError:
              msg: "优惠券已领完，下次早点来"
  /records:
    displayName: 积分收支记录查询
    description: 积分收支记录查询
    get:
      is:
        - respWithData:
            exampleSchema: !include schema/biz/jifen-records.schema
            exampleData: |
              {
                "time": "20160225 17:18:36",
                "activeName": "扫码赚积分",
                "amount": 20,
                "type": 1
              }
  /lucky/{id}:
    displayName: 幸运游戏
    description: 幸运游戏，如大转盘
    uriParameters:
      id:
        displayName: id
        description: 幸运游戏ID
        type: string
        required: true
        example: 123456789
    post:
      is:
        - respWithData:
            exampleSchema: !include schema/biz/jifen-lucky.schema
            exampleData: | 
              {
                "consum": 60,
                "earm": 200,
                "luckyName": "二等奖"
              } 
            
/api/jifen/mall:
    displayName: 积分商城
    description: 积分商城
    
    /list:
      displayName: 分商品列表
      description: 积分商品列表
      get:
        is:
          - paged:
              exampleSchema: !include schema/biz/jifen-mall-list.schema
              exampleList: |
                [{
                  "picUrl": "http://www.yebio.com.cn/mail/123456789",
                  "description": "Ipad 64G WIFI版",
                  "price": 50
                  "detailUrl" : "http://www.yebio.com.cn/mail/detail/123456789"
                }, {
                  "picUrl": "http://www.yebio.com.cn/mail/1234567890",
                  "description": "Iphone 6S Plush 123G 土豪版",
                  "price": 100
                  "detailUrl" : "http://www.yebio.com.cn/mail/detail/1234567890"
                }]
        queryParameters:
          keyWords:
            displayName: keyWords
            description: 检索关键字，多个关键字使用逗号(,)分割
            type: string
            required: false
            example: IPAD
          