#%RAML 0.8
title: 易邦生物
baseUri: http://server/api/
version: v0.1
mediaType: application/json

schemas:
  - respWithoutDataSchema: !include schema/resp-without-data.schema
  - respWithDataSchema: !include schema/resp-with-data.schema
  - respErrorSchema: !include schema/resp-error.schema
  - pagedSchema: !include schema/paged.schema

traits:
  # 接口响应中不包含data
  - respWithoutData:
      responses:
        200:
          body:
            application/json:
              schema: respWithoutDataSchema
              example: |
                {
                  "code": "0"
                }
  # 接口响应中包含data
  - respWithData:
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code": "0",
                  "data" : <<exampleData>>
                }
   # 接口响应错误
  - respError:
      responses:
        500:
          body:
            application/json:
              schema: respErrorSchema
              example: |
                {
                  "code": "9",
                  "msg" : <<msg>>
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>
  # 分页
  - paged:
      queryParameters:
          pageNumber:
            displayName: pageNumber
            description: 查询的页面编码，从1开始.如第六页=6
            type: integer
            minimum: 1
            required: false
            default: 1
            example: 6
          pageSize:
            displayName: pageSize
            description: 查询页面每页显示数据数量，如每页显示二十条数据=20
            type: integer
            maximum: 10 
            required: false
            default: 10
            example: 20
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code" : "0",
                  "data" : {
                    "pageNumber" : 1,
                    "pageSize" : 20,
                    "totalRow" : 362,
                    "list" : <<exampleList>>
                  }
                }
 

  # 查询用户权限
  - queryToken:
      queryParameters:
        username:
          displayName: username
          description: 用户唯一标志，使用32位UUID
          type: string
          required: true
          example: 72297c8842604c059b05d28bfb11d10b
        token:
          displayName: token
          description: 用户令牌
          type: string
          required: true
          example: 245accec3c124642967fe476cef558c4
  - bodyToken:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            username:
              displayName: username
              description: 用户唯一标志，使用32位UUID
              type: string
              required: true
              example: 72297c8842604c059b05d28bfb11d10b
            token:
              displayName: token
              description: 用户令牌
              type: string
              required: true
              example: 245accec3c124642967fe476cef558c4
              
#####################################################################
############################ MDM模块 ################################
#####################################################################

/api/mdm:
  displayName: 基础数据
  description: 基础数据
  /breed:
    displayName: 养殖模块
    description: 养殖模块
    /type:
      displayName: 养殖类型
      description: 养殖类型，如禽类、畜类
      
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-breed-type.schema
              exampleData: |
                [{
                  "id": "10",
                  "name": "禽类"
                }, {
                  "id": "11",
                  "name": "畜类"
                }]
    /genera/{id}:
      displayName: 养殖种类
      description: 养殖种类，如鸡、鸭、鹅
      uriParameters:
        id:
          displayName: id
          description: 养殖类型ID
          type: string
          required: true
          example: 10
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-breed-genera.schema
              exampleData: |
                [{
                  "id": "1001",
                  "name": "鸡"
                }, {
                  "id": "1002",
                  "name": "鸭"
                }, {
                  "id": "1003",
                  "name": "鹅"
                }]
    /variety/{id}:
      displayName: 养殖种类
      description: 养殖种类，如肉鸡、蛋鸡
      uriParameters:
        id:
          displayName: id
          description: 养殖种类ID
          type: string
          required: true
          example: 10
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-breed-variety.schema
              exampleData: |
                [{
                  "id": "100101",
                  "name": "肉鸡"
                }, {
                  "id": "100102",
                  "name": "蛋鸡"
                }]
    
    /amount/{id}:
      displayName: 养殖规模
      description: 养殖规模
      uriParameters:
        id:
          displayName: id
          description: 养殖类型ID
          type: string
          required: true
          example: 10
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-breed-amount.schema
              exampleData: |
                [{
                  "id": "1001",
                  "name": "5000-10000只"
                }, {
                  "id": "1002",
                  "name": "10000-20000只"
                }]
    /style/{id}:
      displayName: 养殖方式
      description: 养殖方式
      uriParameters:
        id:
          displayName: id
          description: 养殖类型ID
          type: string
          required: true
          example: 10
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-breed-style.schema
              exampleData: |
                [{
                  "id": "1001",
                  "name": "地面平养"
                }, {
                  "id": "1002",
                  "name": "圈养"
                }]
  /area:
    displayName: 区域模块
    description: 区域模块，包含查询省份、城市、区县
  
    /provice:
      displayName: 查询34个省
      description: 查询34个省
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-area-provice.schema
              exampleData: |
                [{
                  "provice": "37",
                  "provinceName": "山东"
                }, {
                  "provice": "01",
                  "provinceName": "北京"
                }]
    /city/{id}:
      displayName: 查询省下的城市
      description: 查询省下的城市
      uriParameters:
        id:
          displayName: id
          description: 省份编码
          type: string
          required: true
          example: 37
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-area-city.schema
              exampleData: |
                [{
                  "city": "3701",
                  "cityName": "济南"
                }, {
                  "city": "3702",
                  "cityName": "青岛"
                }]
    /county/{id}:
      displayName: 查询城市下的区县
      description: 查询城市下的区县
      uriParameters:
        id:
          displayName: id
          description: 城市编码
          type: string
          required: true
          example: 3702
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-area-county.schema
              exampleData: |
                [{
                  "county": "370201",
                  "countyName": "市辖区"
                }, {
                  "county": "370202",
                  "countyName": "市南区"
                }, {
                  "county": "370203",
                  "countyName": "市北区"
                }]
    /agency/{id}:
      displayName: 查询区县下的二级经销商
      description: 查询区县下的二级经销商
      uriParameters:
        id:
          displayName: id
          description: 区县编码
          type: string
          required: true
          example: 370203
          
      get:
        is:
          - respWithData:
              exampleSchema: !include schema/biz/mdm-area-agency.schema
              exampleData: |
                {
                  "id": "123456789",
                  "companyName": "易邦生物"
                }
        
