#%RAML 0.8
title: 易邦生物
baseUri: http://server/api/
version: v0.1
mediaType: application/json

schemas:
  - respWithoutDataSchema: !include schema/resp-without-data.schema
  - respWithDataSchema: !include schema/resp-with-data.schema
  - respErrorSchema: !include schema/resp-error.schema
  - pagedSchema: !include schema/paged.schema

traits:
  # 接口响应中不包含data
  - respWithoutData:
      responses:
        200:
          body:
            application/json:
              schema: respWithoutDataSchema
              example: |
                {
                  "code": "0"
                }
  # 接口响应中包含data
  - respWithData:
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code": "0",
                  "data" : <<exampleData>>
                }
   # 接口响应错误
  - respError:
      responses:
        500:
          body:
            application/json:
              schema: respErrorSchema
              example: |
                {
                  "code": "9",
                  "msg" : <<msg>>
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>
  # 分页
  - paged:
      queryParameters:
          pageNumber:
            displayName: pageNumber
            description: 查询的页面编码，从1开始.如第六页=6
            type: integer
            minimum: 1
            required: false
            default: 1
            example: 6
          pageSize:
            displayName: pageSize
            description: 查询页面每页显示数据数量，如每页显示二十条数据=20
            type: integer
            maximum: 10 
            required: false
            default: 10
            example: 20
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code" : "0",
                  "data" : {
                    "pageNumber" : 1,
                    "pageSize" : 20,
                    "totalRow" : 362,
                    "list" : <<exampleList>>
                  }
                }
 

  # 查询用户权限
  - queryToken:
      queryParameters:
        username:
          displayName: username
          description: 用户唯一标志，使用32位UUID
          type: string
          required: true
          example: 72297c8842604c059b05d28bfb11d10b
        token:
          displayName: token
          description: 用户令牌
          type: string
          required: true
          example: 245accec3c124642967fe476cef558c4
  - bodyToken:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            username:
              displayName: username
              description: 用户唯一标志，使用32位UUID
              type: string
              required: true
              example: 72297c8842604c059b05d28bfb11d10b
            token:
              displayName: token
              description: 用户令牌
              type: string
              required: true
              example: 245accec3c124642967fe476cef558c4
              

#####################################################################
############################ 订单模块 ################################
#####################################################################

/api/{username}/{token}/order:
  displayName: 订单模块
  description: 订单模块，包含查询订单列表、订单详情、下订单
  
  uriParameters:
    username:
      displayName: username
      description: 用户唯一标志，使用32位UUID
      type: string
      required: true
      example: 72297c8842604c059b05d28bfb11d10b
    token:
      displayName: token
      description: 用户令牌
      type: string
      required: true
      example: 245accec3c124642967fe476cef558c4
  
  /list:
    displayName: 查询订单列表
    description: 查询订单列表，包含分页
    get:
      is:
        - paged:
            exampleSchema: !include schema/biz/order-list.schema
            exampleList: |
              [{
                "id": "201505160000100151840837",
                "status": "已发货",
                "jifen": "1400",
                "products": [{
                  "id": "123456789",
                  "name": "兽用猪用连续注射器，好用的注射器",
                  "jifen": 500,
                  "amount": 2,
                  "picUrl": "http://www.yebio.com.cn/123456789"
                }, {
                  "id": "1234567890",
                  "name": "畜牧用纯天然橡胶白手套",
                  "jifen": 400,
                  "amount": 1,
                  "picUrl": "http://www.yebio.com.cn/1234567890"
                }]
              }]
      queryParameters:
        orderState:
          displayName: orderState
          description: 订单状态，1已付款，2待收货
          type: integer
          minimum: 1
          required: false
          example: 1
              
  /add:
    displayName: 下订单
    description: 下订单
    post:
      is:
        - respWithData:
            exampleSchema: !include schema/biz/order-add.schema
            exampleData: | 
              {
                "id": "123456789"
              }
        - respError:
            msg: "积分不够"
      body:
        application/x-www-form-urlencoded:
          formParameters:
            data:
              displayName: data
              description: '订单商品信息,
                [{
                  "id": "123456789",
                  "amount": 2
                }, {
                  "id": "1234567890",
                  "amount": 1
                }]'
            address:
              displayName: address
              description: 收货地址ID
              type: string
              required: true
              example: 123456789
            dliveryTme:
              displayName: dliveryTme
              description: 送货时间，工作日1、节假日2、任意时间3
              enum: [1,2,3]
              required: true
              example: 1
  
  /delete/{id}:
    displayName: 删除订单
    description: 删除订单
    
    uriParameters:
      id:
        displayName: id
        description: 订单ID
        type: string
        required: true
        example: 123456789
    delete:
      is:
        - respWithoutData:
  /{id}:
    displayName: 订单详情
    description: 订单详情
    
    uriParameters:
      id:
        displayName: id
        description: 订单ID
        type: string
        required: true
        example: 123456789
    
    get:
      is:
        - respWithData:
            exampleSchema: !include schema/biz/order.schema
            exampleData: | 
              {
                "id": "201505160000100151840837",
                "status": "已发货",
                "jifen": "1400",
                "products": [{
                  "id": "123456789",
                  "name": "兽用猪用连续注射器，好用的注射器",
                  "jifen": 500,
                  "amount": 2,
                  "picUrl": "http://www.yebio.com.cn/123456789"
                }, {
                  "id": "1234567890",
                  "name": "畜牧用纯天然橡胶白手套",
                  "jifen": 400,
                  "amount": 1,
                  "picUrl": "http://www.yebio.com.cn/1234567890"
                }]
              }















