#%RAML 0.8
title: 易邦生物
baseUri: http://server/api/
version: v0.1
mediaType: application/json

schemas:
  - respWithoutDataSchema: !include schema/resp-without-data.schema
  - respWithDataSchema: !include schema/resp-with-data.schema
  - respErrorSchema: !include schema/resp-error.schema
  - pagedSchema: !include schema/paged.schema

traits:
  # 接口响应中不包含data
  - respWithoutData:
      responses:
        200:
          body:
            application/json:
              schema: respWithoutDataSchema
              example: |
                {
                  "code": "0"
                }
  # 接口响应中包含data
  - respWithData:
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code": "0",
                  "data" : <<exampleData>>
                }
   # 接口响应错误
  - respError:
      responses:
        500:
          body:
            application/json:
              schema: respErrorSchema
              example: |
                {
                  "code": "9",
                  "msg" : <<msg>>
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>
  # 分页
  - paged:
      queryParameters:
          pageNumber:
            displayName: pageNumber
            description: 查询的页面编码，从1开始.如第六页=6
            type: integer
            minimum: 1
            required: false
            default: 1
            example: 6
          pageSize:
            displayName: pageSize
            description: 查询页面每页显示数据数量，如每页显示二十条数据=20
            type: integer
            maximum: 10 
            required: false
            default: 10
            example: 20
      responses:
        200:
          body:
            application/json:
              schema: <<exampleSchema>>
              example: |
                {
                  "code" : "0",
                  "data" : {
                    "pageNumber" : 1,
                    "pageSize" : 20,
                    "totalRow" : 362,
                    "list" : <<exampleList>>
                  }
                }
 

  # 查询用户权限
  - queryToken:
      queryParameters:
        username:
          displayName: username
          description: 用户唯一标志，使用32位UUID
          type: string
          required: true
          example: 72297c8842604c059b05d28bfb11d10b
        token:
          displayName: token
          description: 用户令牌
          type: string
          required: true
          example: 245accec3c124642967fe476cef558c4
  - bodyToken:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            username:
              displayName: username
              description: 用户唯一标志，使用32位UUID
              type: string
              required: true
              example: 72297c8842604c059b05d28bfb11d10b
            token:
              displayName: token
              description: 用户令牌
              type: string
              required: true
              example: 245accec3c124642967fe476cef558c4
              
#####################################################################
############################ 用户模块 ################################
#####################################################################
  
/api/user:
  displayName: 用户基本操作
  description: 用户基本操作，包括用户注册，忘记密码，用户登录，用户基本信息查看和修改
  
  /register:
    displayName: 注册
    description: 注册，二级经销商和散户注册
    
    /agency:
      displayName: 二级代理商注册
      description: 二级代理商注册需要填写代理商的地址，包含省份、城市、区县、详细地址、公司名称，还需要注册手机号、手机验证码
      post:
        description: 注册。如果用户已注册，返回500
        is:
          - respWithoutData:
          - respError:
              msg: "手机号已注册"
        body:
          application/x-www-form-urlencoded:
            formParameters:
              phone:
                displayName: phone
                description: 注册手机号
                type: string
                required: true
                example: 15689952699
              checkCode:
                displayName: checkCode
                description: 注册发送的手机验证码
                type: string
                required: true
                example: 356982
              password:
                displayName: password
                description: 密码
                type: string
                required: true
                example: yebio2016
              provice:
                displayName: provice
                description: 省份的编码，如山东=37
                type: string
                required: true
                example: 37
              city:
                displayName: city
                description: 城市的编码，如青岛=02
                type: string
                required: true
                example: 02
              county:
                displayName: county
                description: 区县的编码，如市北区=03
                type: string
                required: true
                example: 03
              name:
                displayName: name
                description: 经销商名称
                type: string
                required: true
                example: 济宁兖州大国兽药饲料服务中心
        
    /custome:
      displayName: 散户注册
      description: 散户注册需要填写散户经营的项目。包含经营的种类，数量等，还需要注册手机号、手机验证码
      post:
        is:
          - respWithoutData:
          - respError:
              msg: "手机号已注册"
        body:
          application/x-www-form-urlencoded:
            formParameters:
              phone:
                displayName: phone
                description: 注册手机号
                type: string
                required: true
                example: 15689952699
              checkCode:
                displayName: checkCode
                description: 注册发送的手机验证码
                type: string
                required: true
                example: 356982
              password:
                displayName: password
                description: 密码
                type: string
                required: true
                example: yebio2016
              type:
                displayName: type
                description: 养殖类型，如禽类=01、畜类=02
                type: string
                required: true
                example: 01
              genera:
                displayName: genera
                description: 养殖种类，如禽类中的鸡0101、鸭0102、鹅0103
                type: string
                required: true
                example: 0101
              variety:
                displayName: variety
                description: 品种，如肉食鸡010101、蛋鸡010102
                type: string
                required: true
                example: 010101
              amount:
                displayName: amount
                description: 养殖规模，如5000-10000只=0101
                type: string
                required: true
                example: 0101
              style:
                displayName: style
                description: 养殖方式，如地面平养=0101
                type: string
                required: true
                example: 0101
                
  /forget:
    displayName: 密码重置
    description: 密码重置，发送短信，使用手机号和短信验证码重置
    post:
      description: 密码重置。如果短信验证码错误，返回500错误
      is:
        - respWithoutData:
        - respError:
            msg: "验证码错误"
      body:
        application/x-www-form-urlencoded:
          formParameters:
            phone:
              displayName: phone
              description: 手机号
              type: string
              required: true
              example: 15689952699
            checkCode:
              displayName: checkCode
              description: 发送的手机验证码
              type: string
              required: true
              example: 356982
            password:
              displayName: password
              description: 密码
              type: string
              required: true
              example: yebio2016    
                      
  /login:
    displayName: 登录
    description: 用户登录，用户名目前为手机号码
    post:
      description: 登录
      is:
        - respWithData:
            exampleSchema: !include schema/biz/user-login.schema
            exampleData: |
              {
                "token" : "123456789"
              }
        - respError:
            msg: "手机号或密码错误"
      body:
        application/x-www-form-urlencoded:
          formParameters:
            phone:
              displayName: phone
              description: 手机号
              type: string
              required: true
              example: 15689952699
            password:
              displayName: password
              description: 密码
              type: string
              required: true
              example: yebio2016
              
  /logout/{username}:
    displayName: 注销
    description: 注销登录
    uriParameters:
      username:
        displayName: username
        description: 用户唯一标志，使用32位UUID
        type: string
        required: true
        example: 72297c8842604c059b05d28bfb11d10b
    post:
      description: 注销
      is:
        - respWithoutData:           
            

/api/{username}/{token}/user:
  displayName: 用户模块
  description: 用户的基本信息，包括基本信息查看，修改头像、修改密码、修改其他基本信息
  uriParameters:
    username:
      displayName: username
      description: 用户唯一标志，使用32位UUID
      type: string
      required: true
      example: 72297c8842604c059b05d28bfb11d10b
    token:
      displayName: token
      description: 用户令牌
      type: string
      required: true
      example: 245accec3c124642967fe476cef558c4
  get:
    description: 查询用户基本信息
    is:
      - respWithData:
          exampleSchema: !include schema/biz/account.schema
          exampleData: |
            {
              "photoUrl" : "http://www.yebio.com.cn/file/5709f0ba31e342bda28d03485b257c9",
              "gender" : "M"
            }
            
  /photo:
    displayName: 修改头像
    description: 修改用户头像，使用文件上传方式提交，修改成功后返回新头像URL
    post:
      is:
        - respWithoutData:
      body:
        multipart/form-data:
          formParameters:
            file:
              displayName: file
              description: 上传文件的Key
              type: string
              required: true
              example: file
              
        
  /password:
    displayName: 修改密码
    description: 修改密码需要原密码，如果原密码错误，返回5000
    post:
      is: 
        - respWithoutData:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            password:
              displayName: password
              description: 密码
              type: string
              required: true
              example: yebio2016
            newPassword:
              displayName: newPassword
              description: 新密码
              type: string
              required: true
              example: Yebio666
  /basic:
    displayName: 修改用户基本信息
    description: 修改用户基本信息
    post:
      is:
        - respWithoutData:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            gender:
              displayName: gender
              description: 性别，M男，F女
              enum: ['M','N']
              required: true
              example: M
              